# Generated by Django 4.0 on 2024-10-08 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=15)),
                ('author_last_name', models.CharField(max_length=15)),
                ('author_surname', models.CharField(max_length=15)),
                ('abbreviation', models.CharField(max_length=25)),
                ('rating', models.FloatField(default=0.0)),
                ('gender', models.CharField(choices=[('Ж', 'Женский'), ('М', 'Мужской')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_cover', models.ImageField(blank=True, upload_to='Book_covers/')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('age_limit', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('description', models.TextField()),
                ('book_author', models.ManyToManyField(to='books.Authors')),
                ('genres', models.ManyToManyField(to='books.Genre')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.imagesbooks')),
            ],
        ),
    ]
