# Generated by Django 4.0 on 2024-10-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
