# Generated by Django 4.0 on 2024-10-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='author_surname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
