# Generated by Django 4.0 on 2024-10-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_books_book_author_books_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='age_limit',
            field=models.IntegerField(default=0),
        ),
    ]
