# Generated by Django 4.0 on 2024-10-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_books_book_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_author',
        ),
        migrations.AddField(
            model_name='books',
            name='book_author',
            field=models.ManyToManyField(to='books.Authors'),
        ),
    ]
